// All 169 Grind 169 problems
// Fields: id (grind order), leetcode (LC number), title, difficulty, acceptance
const PROBLEMS = [
  { id: 1,   leetcode: 1,    title: "Two Sum",                                                    difficulty: "Easy", acceptance: "57.1%" },
  { id: 2,   leetcode: 2,    title: "Add Two Numbers",                                             difficulty: "Med",  acceptance: "48.0%" },
  { id: 3,   leetcode: 3,    title: "Longest Substring Without Repeating Characters",              difficulty: "Med",  acceptance: "38.6%" },
  { id: 4,   leetcode: 4,    title: "Median of Two Sorted Arrays",                                 difficulty: "Hard", acceptance: "46.0%" },
  { id: 5,   leetcode: 5,    title: "Longest Palindromic Substring",                               difficulty: "Med",  acceptance: "37.4%" },
  { id: 6,   leetcode: 7,    title: "Reverse Integer",                                             difficulty: "Med",  acceptance: "31.5%" },
  { id: 7,   leetcode: 8,    title: "String to Integer (atoi)",                                    difficulty: "Med",  acceptance: "20.6%" },
  { id: 8,   leetcode: 9,    title: "Palindrome Number",                                           difficulty: "Easy", acceptance: "60.3%" },
  { id: 9,   leetcode: 11,   title: "Container With Most Water",                                   difficulty: "Med",  acceptance: "59.6%" },
  { id: 10,  leetcode: 994,  title: "Rotting Oranges",                                             difficulty: "Med",  acceptance: "58.2%" },
  { id: 11,  leetcode: 13,   title: "Roman to Integer",                                            difficulty: "Easy", acceptance: "66.3%" },
  { id: 12,  leetcode: 14,   title: "Longest Common Prefix",                                       difficulty: "Easy", acceptance: "47.1%" },
  { id: 13,  leetcode: 15,   title: "3Sum",                                                        difficulty: "Med",  acceptance: "38.6%" },
  { id: 14,  leetcode: 16,   title: "3Sum Closest",                                                difficulty: "Med",  acceptance: "48.1%" },
  { id: 15,  leetcode: 17,   title: "Letter Combinations of a Phone Number",                       difficulty: "Med",  acceptance: "65.6%" },
  { id: 16,  leetcode: 525,  title: "Contiguous Array",                                            difficulty: "Med",  acceptance: "50.9%" },
  { id: 17,  leetcode: 19,   title: "Remove Nth Node From End of List",                            difficulty: "Med",  acceptance: "51.1%" },
  { id: 18,  leetcode: 20,   title: "Valid Parentheses",                                           difficulty: "Easy", acceptance: "43.8%" },
  { id: 19,  leetcode: 21,   title: "Merge Two Sorted Lists",                                      difficulty: "Easy", acceptance: "68.0%" },
  { id: 20,  leetcode: 22,   title: "Generate Parentheses",                                        difficulty: "Med",  acceptance: "78.3%" },
  { id: 21,  leetcode: 23,   title: "Merge k Sorted Lists",                                        difficulty: "Hard", acceptance: "59.0%" },
  { id: 22,  leetcode: 24,   title: "Swap Nodes in Pairs",                                         difficulty: "Med",  acceptance: "69.0%" },
  { id: 23,  leetcode: 25,   title: "Reverse Nodes in k-Group",                                    difficulty: "Hard", acceptance: "65.4%" },
  { id: 24,  leetcode: 542,  title: "01 Matrix",                                                   difficulty: "Med",  acceptance: "53.4%" },
  { id: 25,  leetcode: 31,   title: "Next Permutation",                                            difficulty: "Med",  acceptance: "44.8%" },
  { id: 26,  leetcode: 32,   title: "Longest Valid Parentheses",                                   difficulty: "Hard", acceptance: "38.1%" },
  { id: 27,  leetcode: 33,   title: "Search in Rotated Sorted Array",                              difficulty: "Med",  acceptance: "44.2%" },
  { id: 28,  leetcode: 543,  title: "Diameter of Binary Tree",                                     difficulty: "Easy", acceptance: "65.1%" },
  { id: 29,  leetcode: 36,   title: "Valid Sudoku",                                                difficulty: "Med",  acceptance: "64.2%" },
  { id: 30,  leetcode: 37,   title: "Sudoku Solver",                                               difficulty: "Hard", acceptance: "65.4%" },
  { id: 31,  leetcode: 1730, title: "Shortest Path to Get Food",                                   difficulty: "Med",  acceptance: "57.1%" },
  { id: 32,  leetcode: 39,   title: "Combination Sum",                                             difficulty: "Med",  acceptance: "76.1%" },
  { id: 33,  leetcode: 41,   title: "First Missing Positive",                                      difficulty: "Hard", acceptance: "42.5%" },
  { id: 34,  leetcode: 42,   title: "Trapping Rain Water",                                         difficulty: "Hard", acceptance: "66.9%" },
  { id: 35,  leetcode: 46,   title: "Permutations",                                                difficulty: "Med",  acceptance: "81.7%" },
  { id: 36,  leetcode: 48,   title: "Rotate Image",                                                difficulty: "Med",  acceptance: "79.4%" },
  { id: 37,  leetcode: 49,   title: "Group Anagrams",                                              difficulty: "Med",  acceptance: "72.2%" },
  { id: 38,  leetcode: 50,   title: "Pow(x, n)",                                                   difficulty: "Med",  acceptance: "38.3%" },
  { id: 39,  leetcode: 51,   title: "N-Queens",                                                    difficulty: "Hard", acceptance: "75.0%" },
  { id: 40,  leetcode: 560,  title: "Subarray Sum Equals K",                                       difficulty: "Med",  acceptance: "46.9%" },
  { id: 41,  leetcode: 53,   title: "Maximum Subarray",                                            difficulty: "Med",  acceptance: "53.0%" },
  { id: 42,  leetcode: 54,   title: "Spiral Matrix",                                               difficulty: "Med",  acceptance: "56.2%" },
  { id: 43,  leetcode: 55,   title: "Jump Game",                                                   difficulty: "Med",  acceptance: "40.5%" },
  { id: 44,  leetcode: 56,   title: "Merge Intervals",                                             difficulty: "Med",  acceptance: "51.2%" },
  { id: 45,  leetcode: 57,   title: "Insert Interval",                                             difficulty: "Med",  acceptance: "44.8%" },
  { id: 46,  leetcode: 572,  title: "Subtree of Another Tree",                                     difficulty: "Easy", acceptance: "51.3%" },
  { id: 47,  leetcode: 61,   title: "Rotate List",                                                 difficulty: "Med",  acceptance: "41.3%" },
  { id: 48,  leetcode: 62,   title: "Unique Paths",                                                difficulty: "Med",  acceptance: "66.6%" },
  { id: 49,  leetcode: 67,   title: "Add Binary",                                                  difficulty: "Easy", acceptance: "57.7%" },
  { id: 50,  leetcode: 70,   title: "Climbing Stairs",                                             difficulty: "Easy", acceptance: "53.9%" },
  { id: 51,  leetcode: 73,   title: "Set Matrix Zeroes",                                           difficulty: "Med",  acceptance: "62.5%" },
  { id: 52,  leetcode: 74,   title: "Search a 2D Matrix",                                          difficulty: "Med",  acceptance: "53.6%" },
  { id: 53,  leetcode: 75,   title: "Sort Colors",                                                 difficulty: "Med",  acceptance: "69.2%" },
  { id: 54,  leetcode: 76,   title: "Minimum Window Substring",                                    difficulty: "Hard", acceptance: "47.0%" },
  { id: 55,  leetcode: 588,  title: "Design In-Memory File System",                                difficulty: "Hard", acceptance: "48.4%" },
  { id: 56,  leetcode: 78,   title: "Subsets",                                                     difficulty: "Med",  acceptance: "82.1%" },
  { id: 57,  leetcode: 79,   title: "Word Search",                                                 difficulty: "Med",  acceptance: "46.9%" },
  { id: 58,  leetcode: 84,   title: "Largest Rectangle in Histogram",                              difficulty: "Hard", acceptance: "49.4%" },
  { id: 59,  leetcode: 91,   title: "Decode Ways",                                                 difficulty: "Med",  acceptance: "37.7%" },
  { id: 60,  leetcode: 98,   title: "Validate Binary Search Tree",                                 difficulty: "Med",  acceptance: "35.4%" },
  { id: 61,  leetcode: 100,  title: "Same Tree",                                                   difficulty: "Easy", acceptance: "66.7%" },
  { id: 62,  leetcode: 101,  title: "Symmetric Tree",                                              difficulty: "Easy", acceptance: "60.8%" },
  { id: 63,  leetcode: 102,  title: "Binary Tree Level Order Traversal",                           difficulty: "Med",  acceptance: "72.2%" },
  { id: 64,  leetcode: 103,  title: "Binary Tree Zigzag Level Order Traversal",                    difficulty: "Med",  acceptance: "63.2%" },
  { id: 65,  leetcode: 104,  title: "Maximum Depth of Binary Tree",                                difficulty: "Easy", acceptance: "78.0%" },
  { id: 66,  leetcode: 105,  title: "Construct Binary Tree from Preorder and Inorder Traversal",   difficulty: "Med",  acceptance: "68.4%" },
  { id: 67,  leetcode: 108,  title: "Convert Sorted Array to Binary Search Tree",                  difficulty: "Easy", acceptance: "75.2%" },
  { id: 68,  leetcode: 621,  title: "Task Scheduler",                                              difficulty: "Med",  acceptance: "62.7%" },
  { id: 69,  leetcode: 110,  title: "Balanced Binary Tree",                                        difficulty: "Easy", acceptance: "57.9%" },
  { id: 70,  leetcode: 113,  title: "Path Sum II",                                                 difficulty: "Med",  acceptance: "61.8%" },
  { id: 71,  leetcode: 1197, title: "Minimum Knight Moves",                                        difficulty: "Med",  acceptance: "41.8%" },
  { id: 72,  leetcode: 632,  title: "Smallest Range Covering Elements from K Lists",               difficulty: "Hard", acceptance: "70.1%" },
  { id: 73,  leetcode: 121,  title: "Best Time to Buy and Sell Stock",                             difficulty: "Easy", acceptance: "56.4%" },
  { id: 74,  leetcode: 124,  title: "Binary Tree Maximum Path Sum",                                difficulty: "Hard", acceptance: "42.0%" },
  { id: 75,  leetcode: 125,  title: "Valid Palindrome",                                            difficulty: "Easy", acceptance: "52.8%" },
  { id: 76,  leetcode: 127,  title: "Word Ladder",                                                 difficulty: "Hard", acceptance: "45.0%" },
  { id: 77,  leetcode: 128,  title: "Longest Consecutive Sequence",                                difficulty: "Med",  acceptance: "47.0%" },
  { id: 78,  leetcode: 133,  title: "Clone Graph",                                                 difficulty: "Med",  acceptance: "64.8%" },
  { id: 79,  leetcode: 134,  title: "Gas Station",                                                 difficulty: "Med",  acceptance: "47.6%" },
  { id: 80,  leetcode: 136,  title: "Single Number",                                               difficulty: "Easy", acceptance: "77.4%" },
  { id: 81,  leetcode: 139,  title: "Word Break",                                                  difficulty: "Med",  acceptance: "49.2%" },
  { id: 82,  leetcode: 141,  title: "Linked List Cycle",                                           difficulty: "Easy", acceptance: "53.9%" },
  { id: 83,  leetcode: 143,  title: "Reorder List",                                                difficulty: "Med",  acceptance: "64.7%" },
  { id: 84,  leetcode: 146,  title: "LRU Cache",                                                   difficulty: "Med",  acceptance: "46.9%" },
  { id: 85,  leetcode: 658,  title: "Find K Closest Elements",                                     difficulty: "Med",  acceptance: "49.5%" },
  { id: 86,  leetcode: 148,  title: "Sort List",                                                   difficulty: "Med",  acceptance: "63.9%" },
  { id: 87,  leetcode: 150,  title: "Evaluate Reverse Polish Notation",                            difficulty: "Med",  acceptance: "57.1%" },
  { id: 88,  leetcode: 662,  title: "Maximum Width of Binary Tree",                                difficulty: "Med",  acceptance: "45.3%" },
  { id: 89,  leetcode: 152,  title: "Maximum Product Subarray",                                    difficulty: "Med",  acceptance: "36.0%" },
  { id: 90,  leetcode: 153,  title: "Find Minimum in Rotated Sorted Array",                        difficulty: "Med",  acceptance: "53.9%" },
  { id: 91,  leetcode: 155,  title: "Min Stack",                                                   difficulty: "Med",  acceptance: "57.8%" },
  { id: 92,  leetcode: 169,  title: "Majority Element",                                            difficulty: "Easy", acceptance: "66.1%" },
  { id: 93,  leetcode: 179,  title: "Largest Number",                                              difficulty: "Med",  acceptance: "42.6%" },
  { id: 94,  leetcode: 692,  title: "Top K Frequent Words",                                        difficulty: "Med",  acceptance: "60.0%" },
  { id: 95,  leetcode: 189,  title: "Rotate Array",                                                difficulty: "Med",  acceptance: "44.5%" },
  { id: 96,  leetcode: 190,  title: "Reverse Bits",                                                difficulty: "Easy", acceptance: "67.8%" },
  { id: 97,  leetcode: 191,  title: "Number of 1 Bits",                                            difficulty: "Easy", acceptance: "76.4%" },
  { id: 98,  leetcode: 198,  title: "House Robber",                                                difficulty: "Med",  acceptance: "53.0%" },
  { id: 99,  leetcode: 199,  title: "Binary Tree Right Side View",                                 difficulty: "Med",  acceptance: "69.6%" },
  { id: 100, leetcode: 200,  title: "Number of Islands",                                           difficulty: "Med",  acceptance: "63.9%" },
  { id: 101, leetcode: 206,  title: "Reverse Linked List",                                         difficulty: "Easy", acceptance: "80.3%" },
  { id: 102, leetcode: 207,  title: "Course Schedule",                                             difficulty: "Med",  acceptance: "50.9%" },
  { id: 103, leetcode: 208,  title: "Implement Trie (Prefix Tree)",                                difficulty: "Med",  acceptance: "69.2%" },
  { id: 104, leetcode: 721,  title: "Accounts Merge",                                              difficulty: "Med",  acceptance: "61.0%" },
  { id: 105, leetcode: 210,  title: "Course Schedule II",                                          difficulty: "Med",  acceptance: "55.0%" },
  { id: 106, leetcode: 211,  title: "Design Add and Search Words Data Structure",                  difficulty: "Med",  acceptance: "48.2%" },
  { id: 107, leetcode: 212,  title: "Word Search II",                                              difficulty: "Hard", acceptance: "38.2%" },
  { id: 108, leetcode: 215,  title: "Kth Largest Element in an Array",                             difficulty: "Med",  acceptance: "68.8%" },
  { id: 109, leetcode: 217,  title: "Contains Duplicate",                                          difficulty: "Easy", acceptance: "64.1%" },
  { id: 110, leetcode: 221,  title: "Maximal Square",                                              difficulty: "Med",  acceptance: "50.0%" },
  { id: 111, leetcode: 733,  title: "Flood Fill",                                                  difficulty: "Easy", acceptance: "67.9%" },
  { id: 112, leetcode: 735,  title: "Asteroid Collision",                                          difficulty: "Med",  acceptance: "47.2%" },
  { id: 113, leetcode: 224,  title: "Basic Calculator",                                            difficulty: "Hard", acceptance: "46.6%" },
  { id: 114, leetcode: 226,  title: "Invert Binary Tree",                                          difficulty: "Easy", acceptance: "79.9%" },
  { id: 115, leetcode: 227,  title: "Basic Calculator II",                                         difficulty: "Med",  acceptance: "46.7%" },
  { id: 116, leetcode: 739,  title: "Daily Temperatures",                                          difficulty: "Med",  acceptance: "68.4%" },
  { id: 117, leetcode: 230,  title: "Kth Smallest Element in a BST",                               difficulty: "Med",  acceptance: "76.5%" },
  { id: 118, leetcode: 232,  title: "Implement Queue using Stacks",                                difficulty: "Easy", acceptance: "69.4%" },
  { id: 119, leetcode: 234,  title: "Palindrome Linked List",                                      difficulty: "Easy", acceptance: "57.5%" },
  { id: 120, leetcode: 235,  title: "Lowest Common Ancestor of a Binary Search Tree",              difficulty: "Med",  acceptance: "70.1%" },
  { id: 121, leetcode: 236,  title: "Lowest Common Ancestor of a Binary Tree",                     difficulty: "Med",  acceptance: "68.8%" },
  { id: 122, leetcode: 238,  title: "Product of Array Except Self",                                difficulty: "Med",  acceptance: "68.6%" },
  { id: 123, leetcode: 239,  title: "Sliding Window Maximum",                                      difficulty: "Hard", acceptance: "48.5%" },
  { id: 124, leetcode: 242,  title: "Valid Anagram",                                               difficulty: "Easy", acceptance: "67.8%" },
  { id: 125, leetcode: 759,  title: "Employee Free Time",                                          difficulty: "Hard", acceptance: "72.8%" },
  { id: 126, leetcode: 252,  title: "Meeting Rooms",                                               difficulty: "Easy", acceptance: "59.3%" },
  { id: 127, leetcode: 253,  title: "Meeting Rooms II",                                            difficulty: "Med",  acceptance: "52.6%" },
  { id: 128, leetcode: 261,  title: "Graph Valid Tree",                                            difficulty: "Med",  acceptance: "49.9%" },
  { id: 129, leetcode: 268,  title: "Missing Number",                                              difficulty: "Easy", acceptance: "71.7%" },
  { id: 130, leetcode: 269,  title: "Alien Dictionary",                                            difficulty: "Hard", acceptance: "37.1%" },
  { id: 131, leetcode: 271,  title: "Encode and Decode Strings",                                   difficulty: "Med",  acceptance: "51.2%" },
  { id: 132, leetcode: 278,  title: "First Bad Version",                                           difficulty: "Easy", acceptance: "46.9%" },
  { id: 133, leetcode: 704,  title: "Binary Search",                                               difficulty: "Easy", acceptance: "60.6%" },
  { id: 134, leetcode: 283,  title: "Move Zeroes",                                                 difficulty: "Easy", acceptance: "63.6%" },
  { id: 135, leetcode: 285,  title: "Inorder Successor in BST",                                    difficulty: "Med",  acceptance: "51.1%" },
  { id: 136, leetcode: 287,  title: "Find the Duplicate Number",                                   difficulty: "Med",  acceptance: "64.0%" },
  { id: 137, leetcode: 787,  title: "Cheapest Flights Within K Stops",                             difficulty: "Med",  acceptance: "41.4%" },
  { id: 138, leetcode: 295,  title: "Find Median from Data Stream",                                difficulty: "Hard", acceptance: "54.2%" },
  { id: 139, leetcode: 297,  title: "Serialize and Deserialize Binary Tree",                       difficulty: "Hard", acceptance: "60.4%" },
  { id: 140, leetcode: 300,  title: "Longest Increasing Subsequence",                              difficulty: "Med",  acceptance: "59.1%" },
  { id: 141, leetcode: 310,  title: "Minimum Height Trees",                                        difficulty: "Med",  acceptance: "42.4%" },
  { id: 142, leetcode: 815,  title: "Bus Routes",                                                  difficulty: "Hard", acceptance: "47.2%" },
  { id: 143, leetcode: 322,  title: "Coin Change",                                                 difficulty: "Med",  acceptance: "48.0%" },
  { id: 144, leetcode: 323,  title: "Number of Connected Components in an Undirected Graph",       difficulty: "Med",  acceptance: "64.8%" },
  { id: 145, leetcode: 328,  title: "Odd Even Linked List",                                        difficulty: "Med",  acceptance: "62.3%" },
  { id: 146, leetcode: 329,  title: "Longest Increasing Path in a Matrix",                         difficulty: "Hard", acceptance: "56.4%" },
  { id: 147, leetcode: 1235, title: "Maximum Profit in Job Scheduling",                            difficulty: "Hard", acceptance: "54.6%" },
  { id: 148, leetcode: 336,  title: "Palindrome Pairs",                                            difficulty: "Hard", acceptance: "37.0%" },
  { id: 149, leetcode: 338,  title: "Counting Bits",                                               difficulty: "Easy", acceptance: "80.4%" },
  { id: 150, leetcode: 362,  title: "Design Hit Counter",                                          difficulty: "Med",  acceptance: "69.6%" },
  { id: 151, leetcode: 844,  title: "Backspace String Compare",                                    difficulty: "Easy", acceptance: "49.8%" },
  { id: 152, leetcode: 377,  title: "Combination Sum IV",                                          difficulty: "Med",  acceptance: "55.0%" },
  { id: 153, leetcode: 380,  title: "Insert Delete GetRandom O(1)",                                difficulty: "Med",  acceptance: "55.3%" },
  { id: 154, leetcode: 863,  title: "All Nodes Distance K in Binary Tree",                         difficulty: "Med",  acceptance: "67.5%" },
  { id: 155, leetcode: 383,  title: "Ransom Note",                                                 difficulty: "Easy", acceptance: "65.7%" },
  { id: 156, leetcode: 394,  title: "Decode String",                                               difficulty: "Med",  acceptance: "62.3%" },
  { id: 157, leetcode: 876,  title: "Middle of the Linked List",                                   difficulty: "Easy", acceptance: "81.6%" },
  { id: 158, leetcode: 528,  title: "Random Pick with Weight",                                     difficulty: "Med",  acceptance: "48.9%" },
  { id: 159, leetcode: 409,  title: "Longest Palindrome",                                          difficulty: "Easy", acceptance: "55.9%" },
  { id: 160, leetcode: 416,  title: "Partition Equal Subset Sum",                                  difficulty: "Med",  acceptance: "49.2%" },
  { id: 161, leetcode: 417,  title: "Pacific Atlantic Water Flow",                                 difficulty: "Med",  acceptance: "60.6%" },
  { id: 162, leetcode: 895,  title: "Maximum Frequency Stack",                                     difficulty: "Hard", acceptance: "66.7%" },
  { id: 163, leetcode: 424,  title: "Longest Repeating Character Replacement",                     difficulty: "Med",  acceptance: "59.1%" },
  { id: 164, leetcode: 435,  title: "Non-overlapping Intervals",                                   difficulty: "Med",  acceptance: "56.8%" },
  { id: 165, leetcode: 437,  title: "Path Sum III",                                                difficulty: "Med",  acceptance: "46.3%" },
  { id: 166, leetcode: 438,  title: "Find All Anagrams in a String",                               difficulty: "Med",  acceptance: "53.3%" },
  { id: 167, leetcode: 973,  title: "K Closest Points to Origin",                                  difficulty: "Med",  acceptance: "68.8%" },
  { id: 168, leetcode: 977,  title: "Squares of a Sorted Array",                                   difficulty: "Easy", acceptance: "73.6%" },
  { id: 169, leetcode: 981,  title: "Time Based Key-Value Store",                                  difficulty: "Med",  acceptance: "49.7%" },
];

// Language list (order matters — used for tabs)
const LANGUAGES = ["TypeScript", "Haskell", "Elixir", "Rust", "Scala", "OCaml", "Clojure", "Lisp"];

// IDs that have solutions implemented
const SOLVED_IDS = new Set([1, 2, 3, 4, 5]);
